// src/components/ServersView.vue
<template>
  <div v-if="servers && servers.length > 0" class="space-y-3">
    <h3 class="text-lg font-semibold flex items-center gap-2">
      <Globe class="w-5 h-5" />
      {{ title }}
    </h3>
    
    <div class="space-y-2">
      <Card v-for="(server, idx) in servers" :key="idx" class="p-3">
        <div class="space-y-2">
          <div class="flex items-start gap-2">
            <code class="text-sm font-mono bg-code-bg px-2 py-1 rounded flex-1">
              {{ server.url }}
            </code>
          </div>
          
          <p v-if="server.description" class="text-sm text-muted-foreground">
            {{ server.description }}
          </p>

          <div v-if="server.variables && Object.keys(server.variables).length > 0" class="mt-2 space-y-1">
            <span class="text-xs font-medium">Variables:</span>
            <div
              v-for="[varName, variable] in Object.entries(server.variables)"
              :key="varName"
              class="flex items-center gap-2 text-sm"
            >
              <Badge variant="outline" class="text-xs">{{ varName }}</Badge>
              <span class="text-muted-foreground">default:</span>
              <code class="text-xs">{{ variable.default }}</code>
              <template v-if="variable.enum && variable.enum.length > 1">
                <span class="text-muted-foreground">options:</span>
                <code class="text-xs">[{{ variable.enum.join(', ') }}]</code>
              </template>
            </div>
          </div>
        </div>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Globe } from 'lucide-vue-next'
import Card from './ui/Card.vue'
import Badge from './ui/Badge.vue'
import type { Server } from '@/types/openapi'

interface Props {
  servers: Server[]
  title?: string
}

withDefaults(defineProps<Props>(), {
  title: 'Servers',
})
</script>

// src/components/ServersView.tsx
import { Server } from "@/types/openapi";
import { Card } from "./ui/card";
import { Badge } from "./ui/badge";
import { Globe } from "lucide-react";

interface ServersViewProps {
  servers: Server[];
  title?: string;
}

export function ServersView({ servers, title = "Servers" }: ServersViewProps) {
  if (!servers || servers.length === 0) return null;

  return (
    <div className="space-y-3">
      <h3 className="text-lg font-semibold flex items-center gap-2">
        <Globe className="w-5 h-5" />
        {title}
      </h3>
      
      <div className="space-y-2">
        {servers.map((server, idx) => (
          <Card key={idx} className="p-3">
            <div className="space-y-2">
              <div className="flex items-start gap-2">
                <code className="text-sm font-mono bg-code-bg px-2 py-1 rounded flex-1">
                  {server.url}
                </code>
              </div>
              
              {server.description && (
                <p className="text-sm text-muted-foreground">{server.description}</p>
              )}

              {server.variables && Object.keys(server.variables).length > 0 && (
                <div className="mt-2 space-y-1">
                  <span className="text-xs font-medium">Variables:</span>
                  {Object.entries(server.variables).map(([varName, variable]) => (
                    <div key={varName} className="flex items-center gap-2 text-sm">
                      <Badge variant="outline" className="text-xs">{varName}</Badge>
                      <span className="text-muted-foreground">default:</span>
                      <code className="text-xs">{variable.default}</code>
                      {variable.enum && variable.enum.length > 1 && (
                        <>
                          <span className="text-muted-foreground">options:</span>
                          <code className="text-xs">[{variable.enum.join(', ')}]</code>
                        </>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
